import DesktopNavbar from "./DesktopNavbar";
import Head from "next/head";

const DashboardLayout = () => {
	return (
		<>
		<Head>
				<title>Dashboard Layout</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		<main className="h-full flex flex-col">
			<DesktopNavbar/>
			<h1>Hello world!</h1>
		</main>
		</>
		
	);
};

export default DashboardLayout;
