import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "@supabase/auth-helpers-react";
import { useEffect } from "react";

export default function Home() {
	const router = useRouter();
	const session = useSession();

	useEffect(() => {
		if (session) {
			router.push("/savings");
		} else {
			router.push("/onboarding");
		}
	}, [session]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-full w-full flex-col items-center justify-center">
				<h1>Hello World</h1>
			</main>
		</>
	);
}
