import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { ArrowRightIcon } from "@heroicons/react/24/outline";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import LandingDesktopNavbar from "../components/LandingDesktopNavbar";
import LandingMobileNavbar from "../components/LandingMobileNavbar";
import piggyBankHero from "../public/piggy-bank-hero.png";

export default function Home() {
	const router = useRouter();
	const supabase = useSupabaseClient();
	const session = useSession();

	const [showLogin, setShowLogin] = useState(false);

	useEffect(() => {
		if (session) {
			router.push("/overview");
		}
	}, [session]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favBicon.ico" />
			</Head>
			<main className="isolate h-[200%] bg-[#191E2B]">
				<LandingDesktopNavbar />
				<LandingMobileNavbar />
				{!showLogin ? (
					<div className="flex flex-col overflow-hidden px-[5vw] lg:flex-row lg:gap-0 lg:px-0 lg:pt-[7vw] lg:pl-[10vw]">
						<div className="flex flex-col gap-[4vw] lg:w-1/2 lg:gap-[1.5vw] lg:pr-[8vw]">
							<h1
								className="pt-[10vw] text-left text-[8vw] leading-[11vw] lg:pt-[5vw] lg:text-[3.2vw] lg:leading-[4.1vw]"
								style={{ fontFamily: "Shapiro Light Heavy Wide" }}
							>
								Take your money
								<br></br>
								to the
								<span className="bg-gradient-to-b from-[#07e69b] to-[#10B981] bg-clip-text text-transparent">
									{" "}
									next level
								</span>
							</h1>
							<p className="font-sans text-[3.9vw] text-slate-300 lg:text-[1.25vw] lg:leading-[2vw]">
								Get the app that makes managing your money fun and easy. Frumo's
								gamified tools help you set and achieve personal goals, while
								providing helpful resources for money decisions.
							</p>
							<div className="mb-[10vw] mt-5 flex flex-col gap-[5vw] lg:flex-row lg:gap-[1.4vw] ">
								<button
									className="inline-flex min-w-max items-center justify-center rounded-lg border-2 border-[#11a875] bg-[#11a875] px-7 py-2.5 font-sans text-[3.9vw] font-medium text-white transition-colors hover:border-[#10B981] hover:bg-[#10B981] focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 lg:px-[2.5vw] lg:py-[0.6vw] lg:text-[1.25vw]"
									onClick={() => {
										router.push("/onboarding");
									}}
								>
									Get Started!
								</button>
								<button
									className="inline-flex min-w-max items-center justify-center rounded-lg border-2 border-slate-400 px-7 py-2.5 font-sans text-[3.9vw] font-medium tracking-wide text-slate-300 transition-colors hover:border-white	hover:bg-white hover:text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 lg:px-[2.5vw] lg:py-[0.6vw] lg:text-[1.25vw]"
									onClick={() => setShowLogin(!showLogin)}
								>
									Log In
									<ArrowRightIcon
										className="ml-1.5 -mr-1 h-[4vw] w-[4vw] stroke-[2px] lg:h-[1.25vw] lg:w-[1.25vw] lg:translate-y-[0.07vw]"
										aria-hidden="true"
									/>
								</button>
							</div>
						</div>
						<div className=" flex flex-col justify-center gap-4 max-lg:translate-x-[12vw] sm:min-w-[100px] lg:w-1/2">
							<Image
								src={piggyBankHero}
								// className="h-auto w-full rounded-lg object-cover"
								alt="Frumo Piggy Bank"
							/>
						</div>
						<div className="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden  blur-[64px] sm:top-[-20rem]">
							<svg
								className="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] opacity-60 sm:left-[calc(50%-30rem)] sm:h-[42.375rem]"
								viewBox="0 0 1155 678"
								fill="none"
								xmlns="http://www.w3.org/2000/svg"
							>
								<path
									fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)"
									fillOpacity=".3"
									d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
								/>
								<defs>
									<linearGradient
										id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533"
										x1="1155.49"
										x2="-78.208"
										y1=".177"
										y2="474.645"
										gradientUnits="userSpaceOnUse"
									>
										<stop stopColor="#9089FC" />
										<stop offset={1} stopColor="#FF80B5" />
									</linearGradient>
								</defs>
							</svg>
						</div>
						<div className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-[64px] sm:top-[calc(100%-30rem)]">
							<svg
								className="blur-3xl relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 opacity-60 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]"
								viewBox="0 0 1155 678"
								fill="none"
								xmlns="http://www.w3.org/2000/svg"
							>
								<path
									fill="url(#ecb5b0c9-546c-4772-8c71-4d3f06d544bc)"
									fillOpacity=".3"
									d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z"
								/>
								<defs>
									<linearGradient
										id="ecb5b0c9-546c-4772-8c71-4d3f06d544bc"
										x1="1155.49"
										x2="-78.208"
										y1=".177"
										y2="474.645"
										gradientUnits="userSpaceOnUse"
									>
										<stop stopColor="#9089FC" />
										<stop offset={1} stopColor="#FF80B5" />
									</linearGradient>
								</defs>
							</svg>
						</div>
					</div>
				) : (
					<>
						{/* if showLogin is true, render Auth UI: */}
						<div className="flex h-screen justify-center pt-32">
							<div className="max-w-[480px] rounded-lg px-4">
								<p
									className="text-center text-[27px] text-[#EDEDEE]"
									style={{ fontFamily: "Shapiro Middle Wide", weight: "500" }}
								>
									{"Log in to get your"}
									<br></br>
									{"personalised dashboard!"}
								</p>
								<Auth
									supabaseClient={supabase}
									appearance={{
										theme: ThemeSupa,
										style: {
											button: {
												// --> button needs hover styling if custom colors
												// background: "white",
												// color: "#1e293b",
												// borderColor: "#1e293b",
												// borderWidth: "2px",
												fontSize: "20px",
												borderRadius: "8px",
												fontWeight: "400",
												marginTop: "30px",
												height: "58px",
												paddingTop: "11px",
												letterSpacing: "0.025em",
											},
											label: {
												fontSize: "16px",
												fontWeight: "500",
												color: "#B3B3C1",
												letterSpacing: "0.025em",
												marginTop: "10px",
											},
											input: {
												height: "58px",
												fontSize: "20px",
												color: "#EDEDEE",
												border: "0px",
												backgroundColor: "#282E43",
											},
											anchor: {
												fontSize: "16px",
												paddingTop: "20px",
												color: "#8C939D",
												textDecoration: "none",
												letterSpacing: "0.025em",
											},
										},
									}}
									// theme="dark"
								/>
							</div>
						</div>
					</>
				)}
			</main>
		</>
	);
}
